name: main
on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run lint && npm run format-check
      - run: npm run test:cov
      - run: npm run build
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: github.ref == 'refs/heads/master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        name: "Upload build as artifact"
        if: github.ref == 'refs/heads/master'
        with:
          name: bomberman
          path: ./dist
  Publish:
    name: "Deploy app to github-pages"
    if: github.ref == 'refs/heads/master'
    needs: [TestAndBuild]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bomberman
          path: ./dist
      - name: Deploy app as GithubPages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: false
